### ISSUE TITLE
Libgit fix

### ISSUE THREAD

**Issue by tenspd137** [dallenwilson/trolltoo#1]
Not an issue, but I got it to compile with libgit2-0.26 and quazip-0.7.3-r1.  I have a patch showing the changes necessary.  Basically, libgit2 extended the API to include proxy data for git_remote_connect.  Since fritzing doesn't look like it accounts for it, just fill the function with nullptrs.  Attached is a patch I used and slight modifications to your ebuild.  It was so small, I fiugred I'd just give it to you here and let you decide if you want it or not.

Thanks otherwise - I was having all sorts of problems modifying the ebuild before I cam across this.

Well - it is in a zip anyway :)
[patch.zip](https://github.com/dallenwilson/trolltoo/files/1733347/patch.zip)

**Comment by dallenwilson** [comment]
Sorry for the delay, it's been a busy month.

Does this fix a problem you encountered trying to use this repository/ebuild to install fritzing?

**Comment by tenspd137** [comment]
Well, if libgit is too old, the build will fail.  This fix at least lets it
compile against latest lib git.  I don't think that Fritzing is setup for
proxies, as this (I think) would be the function that handles it.  Like I
said, not an issue, just there 8f you want it.

**Comment by dallenwilson** [comment]
Ah yes, I see now. I had added the older version of libgit2 to this repository because it was no longer available and fritzing required it, but patching fritzing to use a newer version is a much better solution.

That is a good find, I didn't realize it was only one function call that was the problem. I added the patch and update ebuild. Thanks!

**Comment by tenspd137** [comment]
Happy to help 😀

-C
